### PR TITLE
Included Performance Metrics for RaspiBolt under the Bonus section

### PR DESCRIPTION
**Pull request by badokun**
I've added a few components to facilitate performance monitoring. I suspect others may also be interesting in this, especially when doing initial configuration/setup.

It's hard to know what's going on, especially when you first get going and it may seem like things are stuck when they're actually flat-lining the CPU for example. One might even consider this as an earlier setup before running bitcoin and lightning for an improved user experience in setting it all up.

I'm referencing two new resources, `telegraf.conf` and `grafana-dashboard.json` directly in my repository and can update them to point to yours once the pull request has gone thru. 

If you're interested in setting this up yourself, it would be good to confirm it works for another user also.

### CODE REVIEW

**Comment by badokun** [comment]
All good to pull in the change now.

**Comment by Stadicus** [comment]
Sorry about delaying my review, hectic times. I will set this up hopefully next week & am very eager to try & merge it!

**Comment by badokun** [comment]
No problem at all. From my experience the lack of visibility especially
when setting it up the first time pushed me to add this. Sometimes it feels
like nothing is happening when in fact lnd or bitcoind is flat lining the
CPU. :-)

I may explore adding an ELK stack so we have a consolidated place to view
all the logs using a kibana web interface. Just an idea at this point

**Comment by Stadicus** [comment]
Hej @badokun, I went through the guide and set everything up. It works and I learned a lot. I made a lot of additions & changes, commited to the pull-request. In the end however, I question whether it really belongs in the RaspiBolt guide. Installing a lot of software, docker images and config files just to end up with a website displaying CPU & memory monitoring left me utterly underwhelmed.

It seems like this guide is more of a basic setup to your lightning-metrics project. This I find extremely interesting and I will try to set it up, but it's definitely to complex for my beginners guide. 

Setting up the performance monitoring on it's own seems kind of pointless. You could just use `htop` or similar tools for that.

**Comment by badokun** [comment]
Understood, I see your point. Primarily I didn't want to just 'steal' your guide and documenting style for a project of my own so thought it best to pursue this approach with a pull request. 

I'll go ahead and close this pull request and work towards making the lightning-metrics project more comprehensive. 

Thanks for setting the precedent in putting an excellent guide.

**Pull request closed without merging**
