### PR TITLE
Add Connect with String option to Zap Desktop

### PR DESCRIPTION
**Pull request by openoms**
New, quicker option is available since the Zap 0.4.0 beta
No difference for Windows/Unix as only uses the ssh terminal.

### CODE REVIEW

**Comment by Stadicus** [comment]
Thanks, will try this asap

**Comment by Stadicus** [comment]
I definitely would use the binaries provided by lndconnect:
https://github.com/LN-Zap/lndconnect/releases

Building the one executable `lndconnect` from source, including installing Go and other tools, seems overly complicated. Maybe the binaries were not yet available when you wrote the guide?

**Comment by Stadicus** [comment]
It's basically the following commands, could you change that?
```
$ cd /tmp
$ wget https://github.com/LN-Zap/lndconnect/releases/download/v0.1.0/lndconnect-linux-armv7-v0.1.0.tar.gz
$ sudo tar -xvf lndconnect-linux-armv7-v0.1.0.tar.gz --strip=1 -C /usr/local/bin
```

**Comment by openoms** [comment]
Done, thank you. Just could not get to it earlier.

**Comment by Stadicus** [comment]
LGTM! 🎉

**Pull request merged**
